# Generated by Django 3.2.13 on 2022-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('Birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('profile_pic', models.ImageField(upload_to='image')),
                ('country', models.CharField(max_length=20, null=True)),
                ('facebook_profile', models.URLField(null=True)),
            ],
        ),
    ]
