# Generated by Django 3.2.13 on 2022-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0004_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.ImageField(upload_to='profileimage')),
                ('createdByProject', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=200)),
                ('total_target', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[('c', 'Charity'), ('p', 'Personal'), ('t', 'Team Project')], max_length=1)),
                ('create', models.CharField(max_length=20)),
                ('numberOfUsersRated', models.IntegerField(default=0)),
                ('projectRating', models.IntegerField(default=0)),
                ('donations', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('ProjectTitle', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='facebook_profile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(upload_to='profileimage'),
        ),
    ]
