# Generated by Django 3.2.13 on 2022-07-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0005_auto_20220704_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesprject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameproject', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='profileimage')),
            ],
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
