# Generated by Django 3.2.13 on 2022-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0006_auto_20220704_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three')], max_length=5),
        ),
    ]
