# Generated by Django 3.2.13 on 2022-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0007_alter_projects_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameproject', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='donations',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='numberOfUsersRated',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projectRating',
        ),
        migrations.AddField(
            model_name='myuser',
            name='donations',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_pic_main',
            field=models.ImageField(default=1, upload_to='profileimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagesprject',
            name='nameproject',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
