# Generated by Django 3.2.13 on 2022-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdFund', '0013_alter_commentreports_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namecategories', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('adahl', 'adahl'), ('zakat', 'zakat'), ('refugees', 'refugees')], max_length=50),
        ),
    ]
